### PR TITLE
Set AWS_REGION

### LINKED ISSUE #55: AWS SDK region is not correctly set
Controller loads the target region from `AWS_REGION` env variable, but this variable is never set in configuration files. 

https://github.com/aws/aws-cloud-map-mcs-controller-for-k8s/blob/ba9b31ca87969c5bd4e3cdf6259551c9216e36ad/main.go#L90

Error message when running the controller:

> 2021-10-19T23:07:39.211Z        ERROR   controllers.ServiceExport       error when creating new service in Cloud Map    {"serviceexport": "demo/demo-service", "namespace": "demo", "name": "demo-service", "error": "operation error ServiceDiscovery: ListNamespaces, failed to resolve service endpoint, an AWS region is required, but was not found"}

### PR DESCRIPTION
**Pull request by runakash**
*Issue #, if available:* Fixes #55

*Description of changes:*  Adding the support for the environment variable AWS_REGION for the controller running as a docker. Updating the README.md to add more steps, remove outdated information, and simplify examples.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by astaticvoid — APPROVED** [review]

File: Makefile [hunk 1]
```diff
@@ -6,6 +6,8 @@ PKG:=github.com/aws/aws-cloud-map-mcs-controller-for-k8s/pkg/version
 IMG ?= controller:latest
 # Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
 CRD_OPTIONS ?= "crd:trivialVersions=true,preserveUnknownFields=false"
+# AWS Region
+AWS_REGION ?= us-west-2
```
Comment (vanekjar) [inline Makefile:10]: Maybe we should use `us-east-1` as the default region to be aligned with AWS SDK.

File: main.go [hunk 2]
```diff
@@ -86,27 +86,30 @@ func main() {
 	}
 
 	// TODO: configure session
+	awsRegion := os.Getenv("AWS_REGION")
```
Comment (bendu) [inline main.go:89]: Can we infer the region from the EKS cluster if the environment variable is not set? This would allow customers to avoid having to modify files in order to install the controller.

Comment (bendu) [reply main.go:89]: Also, AWS [go SDK](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-the-region) already gets the region from AWS_REGION environment variable. Perhaps we can infer the region from the cluster as a fallback if the SDK itself cannot determine region.

Comment (runakash) [reply main.go:89]: >This would allow customers to avoid having to modify files in order to install the controller

The customer won't have to modify any files, they need to just to set this variable `export AWS_REGION=us-west-2` before applying `kubectl apply -k "github.com/aws/aws-cloud-map-mcs-controller-for-k8s/config/controller_install_release"` or even the following command will work too `AWS_REGION=us-west-2 kubectl apply -k "github.com/aws/aws-cloud-map-mcs-controller-for-k8s/config/controller_install_release"`

Comment (runakash) [reply main.go:89]: > Can we infer the region from the EKS cluster if the environment variable is not set?

We also need to support non-eks cluster setup, and cross region setup.

> AWS go SDK already gets the region from AWS_REGION environment variable

We would still need make this environment variable "available" inside the controller container. Let me tackle fallback separately.

Comment (bendu) [reply main.go:89]: Ok. What happens if `kubectl apply -k ...` is run without setting the environment variable? Does the controller still start? What does the value of the environment variable become?

File: CONTRIBUTING.md [hunk 3]
```diff
@@ -48,48 +79,88 @@ make install
...
-Apply deployment, service and export configs
 ```sh
-kubectl apply -f samples/demo-deployment.yaml
+kubectl apply -f samples/example-deployment.yaml
 # deployment.apps/nginx-deployment created
-kubectl apply -f samples/demo-service.yaml
-# service/demo-service created
-kubectl apply -f samples/demo-export.yaml
-# serviceexport.multicluster.x-k8s.io/demo-service created
+kubectl apply -f samples/example-service.yaml
```
Comment (bendu) [inline CONTRIBUTING.md:92]: README.md needs to be updated to reflect the new file names as well.

File: main.go (hunk 2 above)
Comment (runakash) [reply main.go:89]: Yes, the controller will start. But we will see below error in the controller logs. I haven't deployed in eks cluster though.
```
"operation error ServiceDiscovery: ListNamespaces, failed to resolve service endpoint, an AWS region is required, but was not found"
```
We are talking about implementing fail-fast in case region or credentials are missing.

Comment (bendu) [reply main.go:89]: Thanks for checking.

**Review by bendu — APPROVED** [review]
Happy Friday!

thumbs up
